In [1]:
import pandas as pd
import json
import datetime as dt

# Activity Log

In [2]:
# Take: Each activity has active duration, duration, originalDuration. These will be columns, not sure if they are ever different. If not, just use one.
# coumns from under activityLevel value array that contains same info as above, just need to see if the same.
# Take: activityLevel_sedentary, activityLevel_lightly, activityLevel_fairly, activityLevel_very, each containing minutes
# Take: activityName, activityTypeId, averageHeartRate, calories, 
# from heartRateZones: 
# Take: hrZone_OOR_mins, hrZone_Fatburn_mins, hrZone_Cardio_mins, hrZone_Peak_mins /// hrZone_OOR_cals, hrZone_Fatburn_cals, hrZone_Cardio_cals, hrZone_Peak_cals
# Take: logID, originalStartTime, startTime, steps

In [3]:
#activity_df = pd.read_json('raw_data/get_activities_1.json')
f = open('../data/raw_data/get_activities_1.json')

data = json.load(f)
#print(data['activities'])
activity_df = pd.DataFrame.from_dict(pd.json_normalize(data['activities']), orient='columns')

In [4]:
activity_df.columns

Index(['logId', 'activityTypeId', 'activityName', 'calories', 'steps',
       'averageHeartRate', 'duration', 'activeDuration', 'activityLevel',
       'logType', 'heartRateZones', 'inProgress', 'caloriesLink',
       'heartRateLink', 'tcxLink', 'lastModified', 'startTime',
       'originalStartTime', 'originalDuration', 'elevationGain',
       'hasActiveZoneMinutes', 'manualValuesSpecified.calories',
       'manualValuesSpecified.distance', 'manualValuesSpecified.steps',
       'intervalWorkoutData.intervalSummaries',
       'intervalWorkoutData.numRepeats', 'activeZoneMinutes.totalMinutes',
       'activeZoneMinutes.minutesInHeartRateZones', 'distance', 'speed',
       'pace', 'distanceUnit', 'hasGps', 'source.type', 'source.name',
       'source.id', 'source.url', 'source.trackerFeatures'],
      dtype='object')

In [5]:
dt = list(activity_df.dtypes)
dt

[dtype('int64'),
 dtype('int64'),
 dtype('O'),
 dtype('int64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('bool'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('int64'),
 dtype('float64'),
 dtype('bool'),
 dtype('bool'),
 dtype('bool'),
 dtype('bool'),
 dtype('O'),
 dtype('int64'),
 dtype('int64'),
 dtype('O'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O')]

In [6]:
activity_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 38 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   logId                                      100 non-null    int64
 1   activityTypeId                             100 non-null    int64
 2   activityName                               100 non-null    object
 3   calories                                   100 non-null    int64
 4   steps                                      99 non-null     float64
 5   averageHeartRate                           100 non-null    int64
 6   duration                                   100 non-null    int64
 7   activeDuration                             100 non-null    int64
 8   activityLevel                              100 non-null    object
 9   logType                                    100 non-null    object
 10  heartRateZones                             100 non-null    object
 11  inProgress                                 100 non-null    bool
 12  caloriesLink                               100 non-null    object
 13  heartRateLink                              100 non-null    object
 14  tcxLink                                    100 non-null    object
 15  lastModified                               100 non-null    object
 16  startTime                                  100 non-null    object
 17  originalStartTime                          100 non-null    object
 18  originalDuration                           100 non-null    int64
 19  elevationGain                              100 non-null    float64
 20  hasActiveZoneMinutes                       100 non-null    bool
 21  manualValuesSpecified.calories             100 non-null    bool
 22  manualValuesSpecified.distance             100 non-null    bool
 23  manualValuesSpecified.steps                100 non-null    bool
 24  intervalWorkoutData.intervalSummaries      100 non-null    object
 25  intervalWorkoutData.numRepeats             100 non-null    int64
 26  activeZoneMinutes.totalMinutes             100 non-null    int64
 27  activeZoneMinutes.minutesInHeartRateZones  100 non-null    object
 28  distance                                   1 non-null      float64
 29  speed                                      1 non-null      float64
 30  pace                                       1 non-null      float64
 31  distanceUnit                               1 non-null      object
 32  hasGps                                     1 non-null      object
 33  source.type                                1 non-null      object
 34  source.name                                1 non-null      object
 35  source.id                                  1 non-null      object
 36  source.url                                 1 non-null      object
 37  source.trackerFeatures                     1 non-null      object
dtypes: bool(5), float64(5), int64(9), object(19)
memory usage: 26.4+ KB

In [7]:
activity_df.head(2)

,logId,activityTypeId,activityName,calories,steps,averageHeartRate,duration,activeDuration,activityLevel,logType,...,distance,speed,pace,distanceUnit,hasGps,source.type,source.name,source.id,source.url,source.trackerFeatures
0,5928106317854316648,90013,Walk,562,4874.0,129,3840000,3840000,"[{'minutes': 3, 'name': 'sedentary'}, {'minute...",auto_detected,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5728109325346855272,90013,Walk,125,1142.0,104,1024000,1024000,"[{'minutes': 1, 'name': 'sedentary'}, {'minute...",auto_detected,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
activity_df.drop(['caloriesLink', 'heartRateLink', 'lastModified', 'logType', 'tcxLink', 'manualValuesSpecified.calories', 'manualValuesSpecified.distance', 'manualValuesSpecified.steps', 'source.id', 'source.name', 'source.trackerFeatures', 'source.type', 'source.url'], axis=1, inplace=True)
activity_df.columns

Index(['logId', 'activityTypeId', 'activityName', 'calories', 'steps',
       'averageHeartRate', 'duration', 'activeDuration', 'activityLevel',
       'heartRateZones', 'inProgress', 'startTime', 'originalStartTime',
       'originalDuration', 'elevationGain', 'hasActiveZoneMinutes',
       'intervalWorkoutData.intervalSummaries',
       'intervalWorkoutData.numRepeats', 'activeZoneMinutes.totalMinutes',
       'activeZoneMinutes.minutesInHeartRateZones', 'distance', 'speed',
       'pace', 'distanceUnit', 'hasGps'],
      dtype='object')

In [9]:
f = open('../data/raw_data/get_activities_2.json')
data = json.load(f)
activity_df_2 = pd.DataFrame.from_dict(pd.json_normalize(data['activities']), orient='columns')

f = open('../data/raw_data/get_activities_3.json')
data = json.load(f)
activity_df_3 = pd.DataFrame.from_dict(pd.json_normalize(data['activities']), orient='columns')

In [10]:
activity_df_2.drop(['caloriesLink', 'heartRateLink', 'lastModified', 'logType', 'tcxLink', 'manualValuesSpecified.calories', 'manualValuesSpecified.distance', 'manualValuesSpecified.steps'], axis=1, inplace=True)
activity_df_3.drop(['caloriesLink', 'heartRateLink', 'lastModified', 'logType', 'tcxLink', 'manualValuesSpecified.calories', 'manualValuesSpecified.distance', 'manualValuesSpecified.steps'], axis=1, inplace=True)

In [11]:
print(activity_df.columns)
print(activity_df_2.columns)
print(activity_df_3.columns)

print(activity_df.info())
print(activity_df_2.info())
print(activity_df_3.info())

Index(['logId', 'activityTypeId', 'activityName', 'calories', 'steps',
       'averageHeartRate', 'duration', 'activeDuration', 'activityLevel',
       'heartRateZones', 'inProgress', 'startTime', 'originalStartTime',
       'originalDuration', 'elevationGain', 'hasActiveZoneMinutes',
       'intervalWorkoutData.intervalSummaries',
       'intervalWorkoutData.numRepeats', 'activeZoneMinutes.totalMinutes',
       'activeZoneMinutes.minutesInHeartRateZones', 'distance', 'speed',
       'pace', 'distanceUnit', 'hasGps'],
      dtype='object')
Index(['logId', 'activityTypeId', 'activityName', 'calories', 'steps',
       'averageHeartRate', 'duration', 'activeDuration', 'activityLevel',
       'heartRateZones', 'inProgress', 'startTime', 'originalStartTime',
       'originalDuration', 'elevationGain', 'hasActiveZoneMinutes',
       'intervalWorkoutData.intervalSummaries',
       'intervalWorkoutData.numRepeats', 'activeZoneMinutes.totalMinutes',
       'activeZoneMinutes.minutesInHeartRateZones'],
      dtype='object')
Index(['logId', 'activityTypeId', 'activityName', 'calories', 'steps',
       'averageHeartRate', 'duration', 'activeDuration', 'activityLevel',
       'heartRateZones', 'inProgress', 'startTime', 'originalStartTime',
       'originalDuration', 'elevationGain', 'hasActiveZoneMinutes',
       'intervalWorkoutData.intervalSummaries',
       'intervalWorkoutData.numRepeats', 'activeZoneMinutes.totalMinutes',
       'activeZoneMinutes.minutesInHeartRateZones'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 25 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   logId                                      100 non-null    int64
 1   activityTypeId                             100 non-null    int64
 2   activityName                               100 non-null    object
 3   calories                                   100 non-null    int64
 4   steps                                      99 non-null     float64
 5   averageHeartRate                           100 non-null    int64
 6   duration                                   100 non-null    int64
 7   activeDuration                             100 non-null    int64
 8   activityLevel                              100 non-null    object
 9   heartRateZones                             100 non-null    object
 10  inProgress                                 100 non-null    bool
 11  startTime                                  100 non-null    object
 12  originalStartTime                          100 non-null    object
 13  originalDuration                           100 non-null    int64
 14  elevationGain                              100 non-null    float64
 15  hasActiveZoneMinutes                       100 non-null    bool
 16  intervalWorkoutData.intervalSummaries      100 non-null    object
 17  intervalWorkoutData.numRepeats             100 non-null    int64
 18  activeZoneMinutes.totalMinutes             100 non-null    int64
 19  activeZoneMinutes.minutesInHeartRateZones  100 non-null    object
 20  distance                                   1 non-null      float64
 21  speed                                      1 non-null      float64
 22  pace                                       1 non-null      float64
 23  distanceUnit                               1 non-null      object
 24  hasGps                                     1 non-null      object
dtypes: bool(2), float64(5), int64(9), object(9)
memory usage: 18.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   logId                                      100 non-null    int64
 1   activityTypeId                             100 non-null    int64
 2   activityName                               100 non-null    object
 3   calories                                   100 non-null    int64
 4   steps                                      100 non-null    int64
 5   averageHeartRate                           100 non-null    int64
 6   duration                                   100 non-null    int64
 7   activeDuration                             100 non-null    int64
 8   activityLevel                              100 non-null    object
 9   heartRateZones                             100 non-null    object
 10  inProgress                                 100 non-null    bool
 11  startTime                                  100 non-null    object
 12  originalStartTime                          100 non-null    object
 13  originalDuration                           100 non-null    int64
 14  elevationGain                              100 non-null    float64
 15  hasActiveZoneMinutes                       100 non-null    bool
 16  intervalWorkoutData.intervalSummaries      100 non-null    object
 17  intervalWorkoutData.numRepeats             100 non-null    int64
 18  activeZoneMinutes.totalMinutes             100 non-null    int64
 19  activeZoneMinutes.minutesInHeartRateZones  100 non-null    object
dtypes: bool(2), float64(1), int64(10), object(7)
memory usage: 14.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   logId                                      100 non-null    int64
 1   activityTypeId                             100 non-null    int64
 2   activityName                               100 non-null    object
 3   calories                                   100 non-null    int64
 4   steps                                      100 non-null    int64
 5   averageHeartRate                           100 non-null    int64
 6   duration                                   100 non-null    int64
 7   activeDuration                             100 non-null    int64
 8   activityLevel                              100 non-null    object
 9   heartRateZones                             100 non-null    object
 10  inProgress                                 100 non-null    bool
 11  startTime                                  100 non-null    object
 12  originalStartTime                          100 non-null    object
 13  originalDuration                           100 non-null    int64
 14  elevationGain                              100 non-null    float64
 15  hasActiveZoneMinutes                       100 non-null    bool
 16  intervalWorkoutData.intervalSummaries      100 non-null    object
 17  intervalWorkoutData.numRepeats             100 non-null    int64
 18  activeZoneMinutes.totalMinutes             100 non-null    int64
 19  activeZoneMinutes.minutesInHeartRateZones  100 non-null    object
dtypes: bool(2), float64(1), int64(10), object(7)
memory usage: 14.4+ KB
None

In [12]:
#Dropping because there are only 2-3 instances where this data is recorded, therefore it is useless.
activity_df.drop(['distance', 'distanceUnit', 'elevationGain', 'pace', 'speed'], axis=1, inplace=True)

In [13]:
activity_df = pd.concat([activity_df, activity_df_2, activity_df_3], ignore_index=True)

In [14]:
activity_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   logId                                      300 non-null    int64
 1   activityTypeId                             300 non-null    int64
 2   activityName                               300 non-null    object
 3   calories                                   300 non-null    int64
 4   steps                                      299 non-null    float64
 5   averageHeartRate                           300 non-null    int64
 6   duration                                   300 non-null    int64
 7   activeDuration                             300 non-null    int64
 8   activityLevel                              300 non-null    object
 9   heartRateZones                             300 non-null    object
 10  inProgress                                 300 non-null    bool
 11  startTime                                  300 non-null    object
 12  originalStartTime                          300 non-null    object
 13  originalDuration                           300 non-null    int64
 14  hasActiveZoneMinutes                       300 non-null    bool
 15  intervalWorkoutData.intervalSummaries      300 non-null    object
 16  intervalWorkoutData.numRepeats             300 non-null    int64
 17  activeZoneMinutes.totalMinutes             300 non-null    int64
 18  activeZoneMinutes.minutesInHeartRateZones  300 non-null    object
 19  hasGps                                     1 non-null      object
 20  elevationGain                              200 non-null    float64
dtypes: bool(2), float64(2), int64(9), object(8)
memory usage: 45.2+ KB

In [15]:
#Examine data, clean are next steps for activity.

In [16]:
#print(type(activity_df['activeZoneMinutes.minutesInHeartRateZones'].iloc[0]))
#print(activity_df['activeZoneMinutes.minutesInHeartRateZones'].iloc[0])
print(activity_df['heartRateZones'].iloc[0])
print(activity_df['activityLevel'].iloc[0])

[{'minutes': 0, 'caloriesOut': 10.698376, 'name': 'Out of Range', 'min': 30, 'max': 220}, {'minutes': 10, 'caloriesOut': 68.365232, 'name': 'Fat Burn', 'min': 30, 'max': 220}, {'minutes': 54, 'caloriesOut': 494.604188, 'name': 'Cardio', 'min': 30, 'max': 220}, {'minutes': 0, 'caloriesOut': 0.0, 'name': 'Peak', 'min': 30, 'max': 220}]
[{'minutes': 3, 'name': 'sedentary'}, {'minutes': 5, 'name': 'lightly'}, {'minutes': 7, 'name': 'fairly'}, {'minutes': 49, 'name': 'very'}]

In [17]:
# Plan: 
# pre-generate column names, in a way that can be scripted generated...
# for minutes in heartratezones each element in the array is a dictionary, so iterate through that, check the zoneName, then 
# for that column add the value. iterate in order of index of large array. Should end up with same length

In [18]:
base_column_string = 'heartRateZones'
activity_df['heartRateZones.OutofRange.calories'] = None
activity_df['heartRateZones.FatBurn.calories'] = None
activity_df['heartRateZones.Cardio.calories'] = None
activity_df['heartRateZones.Peak.calories'] = None

activity_df['heartRateZones.OutofRange.minutes'] = None
activity_df['heartRateZones.FatBurn.minutes'] = None
activity_df['heartRateZones.Cardio.minutes'] = None
activity_df['heartRateZones.Peak.minutes'] = None


for index in range(0, len(activity_df['heartRateZones'])):
    data_list = activity_df['heartRateZones'].iloc[index]
    for small_dict in data_list:
        generated_base_col_string = base_column_string + '.' + small_dict['name']
        generated_base_col_string = generated_base_col_string.replace(" ", "")
        
        cal_val = small_dict['caloriesOut']
        #activity_df[generated_base_col_string + '.' + 'calories'].iloc[index] = cal_val
        activity_df.iloc[index, activity_df.columns.get_loc(generated_base_col_string + '.' + 'calories')] = cal_val
        
        minute_val = small_dict['minutes']
        #activity_df[generated_base_col_string + '.' + 'minutes'].iloc[index] = minute_val   
        activity_df.iloc[index, activity_df.columns.get_loc(generated_base_col_string + '.' + 'minutes')] = minute_val

In [19]:
print(activity_df.info())
activity_df.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 29 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   logId                                      300 non-null    int64
 1   activityTypeId                             300 non-null    int64
 2   activityName                               300 non-null    object
 3   calories                                   300 non-null    int64
 4   steps                                      299 non-null    float64
 5   averageHeartRate                           300 non-null    int64
 6   duration                                   300 non-null    int64
 7   activeDuration                             300 non-null    int64
 8   activityLevel                              300 non-null    object
 9   heartRateZones                             300 non-null    object
 10  inProgress                                 300 non-null    bool
 11  startTime                                  300 non-null    object
 12  originalStartTime                          300 non-null    object
 13  originalDuration                           300 non-null    int64
 14  hasActiveZoneMinutes                       300 non-null    bool
 15  intervalWorkoutData.intervalSummaries      300 non-null    object
 16  intervalWorkoutData.numRepeats             300 non-null    int64
 17  activeZoneMinutes.totalMinutes             300 non-null    int64
 18  activeZoneMinutes.minutesInHeartRateZones  300 non-null    object
 19  hasGps                                     1 non-null      object
 20  elevationGain                              200 non-null    float64
 21  heartRateZones.OutofRange.calories         300 non-null    object
 22  heartRateZones.FatBurn.calories            300 non-null    object
 23  heartRateZones.Cardio.calories             300 non-null    object
 24  heartRateZones.Peak.calories               300 non-null    object
 25  heartRateZones.OutofRange.minutes          300 non-null    object
 26  heartRateZones.FatBurn.minutes             300 non-null    object
 27  heartRateZones.Cardio.minutes              300 non-null    object
 28  heartRateZones.Peak.minutes                300 non-null    object
dtypes: bool(2), float64(2), int64(9), object(16)
memory usage: 64.0+ KB
None

,logId,activityTypeId,activityName,calories,steps,averageHeartRate,duration,activeDuration,activityLevel,heartRateZones,...,hasGps,elevationGain,heartRateZones.OutofRange.calories,heartRateZones.FatBurn.calories,heartRateZones.Cardio.calories,heartRateZones.Peak.calories,heartRateZones.OutofRange.minutes,heartRateZones.FatBurn.minutes,heartRateZones.Cardio.minutes,heartRateZones.Peak.minutes
0,5928106317854316648,90013,Walk,562,4874.0,129,3840000,3840000,"[{'minutes': 3, 'name': 'sedentary'}, {'minute...","[{'minutes': 0, 'caloriesOut': 10.698376, 'nam...",...,NaN,NaN,10.698376,68.365232,494.604188,0.0,0,10,54,0
1,5728109325346855272,90013,Walk,125,1142.0,104,1024000,1024000,"[{'minutes': 1, 'name': 'sedentary'}, {'minute...","[{'minutes': 4, 'caloriesOut': 40.44508, 'name...",...,NaN,NaN,40.44508,93.676024,0.0,0.0,4,13,0,0
2,465991347574409752,90009,Run,65,536.0,110,552000,546000,"[{'minutes': 3, 'name': 'sedentary'}, {'minute...","[{'minutes': 3, 'caloriesOut': 15.264756, 'nam...",...,True,NaN,15.264756,43.315376,6.5234,0.0,3,5,1,0
3,6746036796463210008,90013,Walk,186,1615.0,124,1229000,1229000,"[{'minutes': 1, 'name': 'sedentary'}, {'minute...","[{'minutes': 0, 'caloriesOut': 11.481184, 'nam...",...,NaN,NaN,11.481184,104.3744,82.19484,0.0,0,12,8,0
4,2637491738621487072,90013,Walk,135,1405.0,107,972000,972000,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...","[{'minutes': 6, 'caloriesOut': 54.927028, 'nam...",...,NaN,NaN,54.927028,78.802672,9.654632,0.0,6,9,1,0
5,5858760697023012392,90013,Walk,196,1802.0,113,1434000,1434000,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...","[{'minutes': 0, 'caloriesOut': 18.787392, 'nam...",...,NaN,NaN,18.787392,186.960644,0.0,0.0,0,23,0,0
6,7431123456730471784,90013,Walk,146,1607.0,116,1075000,1075000,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...","[{'minutes': 0, 'caloriesOut': 8.610888, 'name...",...,NaN,NaN,8.610888,146.906968,0.0,0.0,0,18,0,0
7,8039486754772653352,90013,Walk,163,1656.0,123,1279000,1279000,"[{'minutes': 2, 'name': 'sedentary'}, {'minute...","[{'minutes': 0, 'caloriesOut': 8.871824, 'name...",...,NaN,NaN,8.871824,129.554724,34.443552,0.0,0,16,5,0
8,8978085603615837832,90013,Walk,237,2699.0,114,1689000,1689000,"[{'minutes': 2, 'name': 'sedentary'}, {'minute...","[{'minutes': 4, 'caloriesOut': 44.098184, 'nam...",...,NaN,NaN,44.098184,192.309832,10.43744,0.0,4,22,2,0
9,4611447219654929608,90013,Walk,144,1266.0,135,921000,921000,"[{'minutes': 1, 'name': 'sedentary'}, {'minute...","[{'minutes': 0, 'caloriesOut': 8.871824, 'name...",...,NaN,NaN,8.871824,0.0,144.689012,0.0,0,0,15,0
10,5102955297776015384,90013,Walk,140,1324.0,129,921000,921000,"[{'minutes': 1, 'name': 'sedentary'}, {'minute...","[{'minutes': 0, 'caloriesOut': 9.393696, 'name...",...,NaN,NaN,9.393696,0.0,140.644504,0.0,0,1,14,0
11,2981123178648656896,90013,Walk,131,1383.0,121,922000,922000,"[{'minutes': 1, 'name': 'sedentary'}, {'minute...","[{'minutes': 0, 'caloriesOut': 9.13276, 'name'...",...,NaN,NaN,9.13276,121.857112,9.915568,0.0,0,14,1,0
12,7985112524605778272,90013,Walk,161,1773.0,107,1330000,1330000,"[{'minutes': 2, 'name': 'sedentary'}, {'minute...","[{'minutes': 6, 'caloriesOut': 40.053676, 'nam...",...,NaN,NaN,40.053676,129.946128,0.0,0.0,6,16,0,0
13,5283503018668279464,90013,Walk,143,1396.0,120,1075000,1075000,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...","[{'minutes': 0, 'caloriesOut': 14.612416, 'nam...",...,NaN,NaN,14.612416,81.672968,55.579368,0.0,0,11,6,0
14,3005736598820620336,90013,Walk,147,1462.0,128,1023000,1023000,"[{'minutes': 2, 'name': 'sedentary'}, {'minute...","[{'minutes': 0, 'caloriesOut': 9.13276, 'name'...",...,NaN,NaN,9.13276,39.401336,108.549376,0.0,0,4,13,0

In [20]:
#Steps is missing from two rows... since its only two I decided to remove the rows, still have plenty of samples.
#Upon further examination, I noticed that some columns aren't the right data type, quick fix.

In [21]:
activity_df = activity_df.dropna()

In [22]:
activity_df.drop(['activeZoneMinutes.minutesInHeartRateZones', 'activeZoneMinutes.totalMinutes', 'activityLevel', 'heartRateZones'], axis=1, inplace=True)
print(activity_df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 25 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   logId                                  0 non-null      int64
 1   activityTypeId                         0 non-null      int64
 2   activityName                           0 non-null      object
 3   calories                               0 non-null      int64
 4   steps                                  0 non-null      float64
 5   averageHeartRate                       0 non-null      int64
 6   duration                               0 non-null      int64
 7   activeDuration                         0 non-null      int64
 8   inProgress                             0 non-null      bool
 9   startTime                              0 non-null      object
 10  originalStartTime                      0 non-null      object
 11  originalDuration                       0 non-null      int64
 12  hasActiveZoneMinutes                   0 non-null      bool
 13  intervalWorkoutData.intervalSummaries  0 non-null      object
 14  intervalWorkoutData.numRepeats         0 non-null      int64
 15  hasGps                                 0 non-null      object
 16  elevationGain                          0 non-null      float64
 17  heartRateZones.OutofRange.calories     0 non-null      object
 18  heartRateZones.FatBurn.calories        0 non-null      object
 19  heartRateZones.Cardio.calories         0 non-null      object
 20  heartRateZones.Peak.calories           0 non-null      object
 21  heartRateZones.OutofRange.minutes      0 non-null      object
 22  heartRateZones.FatBurn.minutes         0 non-null      object
 23  heartRateZones.Cardio.minutes          0 non-null      object
 24  heartRateZones.Peak.minutes            0 non-null      object
dtypes: bool(2), float64(2), int64(8), object(13)
memory usage: 0.0+ bytes
None

In [23]:
activity_df = activity_df.astype({'heartRateZones.OutofRange.calories': 'float', 'heartRateZones.FatBurn.calories': 'float','heartRateZones.Cardio.calories': 'float', 'heartRateZones.Peak.calories': 'float'})

In [24]:
activity_df = activity_df.astype({'heartRateZones.OutofRange.minutes': 'int','heartRateZones.FatBurn.minutes': 'int','heartRateZones.Cardio.minutes': 'int','heartRateZones.Peak.minutes': 'int',})

In [25]:
print(activity_df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 25 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   logId                                  0 non-null      int64
 1   activityTypeId                         0 non-null      int64
 2   activityName                           0 non-null      object
 3   calories                               0 non-null      int64
 4   steps                                  0 non-null      float64
 5   averageHeartRate                       0 non-null      int64
 6   duration                               0 non-null      int64
 7   activeDuration                         0 non-null      int64
 8   inProgress                             0 non-null      bool
 9   startTime                              0 non-null      object
 10  originalStartTime                      0 non-null      object
 11  originalDuration                       0 non-null      int64
 12  hasActiveZoneMinutes                   0 non-null      bool
 13  intervalWorkoutData.intervalSummaries  0 non-null      object
 14  intervalWorkoutData.numRepeats         0 non-null      int64
 15  hasGps                                 0 non-null      object
 16  elevationGain                          0 non-null      float64
 17  heartRateZones.OutofRange.calories     0 non-null      float64
 18  heartRateZones.FatBurn.calories        0 non-null      float64
 19  heartRateZones.Cardio.calories         0 non-null      float64
 20  heartRateZones.Peak.calories           0 non-null      float64
 21  heartRateZones.OutofRange.minutes      0 non-null      int32
 22  heartRateZones.FatBurn.minutes         0 non-null      int32
 23  heartRateZones.Cardio.minutes          0 non-null      int32
 24  heartRateZones.Peak.minutes            0 non-null      int32
dtypes: bool(2), float64(6), int32(4), int64(8), object(5)
memory usage: 0.0+ bytes
None

In [26]:
print(activity_df.columns)
print(list(activity_df.dtypes))

Index(['logId', 'activityTypeId', 'activityName', 'calories', 'steps',
       'averageHeartRate', 'duration', 'activeDuration', 'inProgress',
       'startTime', 'originalStartTime', 'originalDuration',
       'hasActiveZoneMinutes', 'intervalWorkoutData.intervalSummaries',
       'intervalWorkoutData.numRepeats', 'hasGps', 'elevationGain',
       'heartRateZones.OutofRange.calories', 'heartRateZones.FatBurn.calories',
       'heartRateZones.Cardio.calories', 'heartRateZones.Peak.calories',
       'heartRateZones.OutofRange.minutes', 'heartRateZones.FatBurn.minutes',
       'heartRateZones.Cardio.minutes', 'heartRateZones.Peak.minutes'],
      dtype='object')
[dtype('int64'), dtype('int64'), dtype('O'), dtype('int64'), dtype('float64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('bool'), dtype('O'), dtype('O'), dtype('int64'), dtype('bool'), dtype('O'), dtype('int64'), dtype('O'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('int32'), dtype('int32'), dtype('int32'), dtype('int32')]

In [27]:
#make sure to drop this
activity_df['inProgress'].value_counts()

Series([], Name: count, dtype: int64)

# Sleep Log

In [28]:
# Take endtime, startTime, duration, efficiency, isMainSleep
# under leveles, data, array of data times of each cycle of sleep. record that as well.
# Take level (will be light, wake, deep, REM) and datetime /// Likely these two will be PK for each row. Group by endtime, startTime for total sleep day.

In [29]:
f = open('../data/raw_data/get_sleep_1.json')
data = json.load(f)
sleep_df = pd.DataFrame.from_dict(pd.json_normalize(data['sleep']), orient='columns')

f = open('../data/raw_data/get_sleep_2.json')
data = json.load(f)
sleep_df_2 = pd.DataFrame.from_dict(pd.json_normalize(data['sleep']), orient='columns')

f = open('../data/raw_data/get_sleep_3.json')
data = json.load(f)
sleep_df_3 = pd.DataFrame.from_dict(pd.json_normalize(data['sleep']), orient='columns')

In [30]:
print(sleep_df.info())
print(sleep_df_2.info())
print(sleep_df_3.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 35 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   dateOfSleep                               100 non-null    object
 1   duration                                  100 non-null    int64
 2   efficiency                                100 non-null    int64
 3   endTime                                   100 non-null    object
 4   infoCode                                  100 non-null    int64
 5   isMainSleep                               100 non-null    bool
 6   logId                                     100 non-null    int64
 7   logType                                   100 non-null    object
 8   minutesAfterWakeup                        100 non-null    int64
 9   minutesAsleep                             100 non-null    int64
 10  minutesAwake                              100 non-null    int64
 11  minutesToFallAsleep                       100 non-null    int64
 12  startTime                                 100 non-null    object
 13  timeInBed                                 100 non-null    int64
 14  type                                      100 non-null    object
 15  levels.data                               100 non-null    object
 16  levels.shortData                          95 non-null     object
 17  levels.summary.deep.count                 95 non-null     float64
 18  levels.summary.deep.minutes               95 non-null     float64
 19  levels.summary.deep.thirtyDayAvgMinutes   95 non-null     float64
 20  levels.summary.light.count                95 non-null     float64
 21  levels.summary.light.minutes              95 non-null     float64
 22  levels.summary.light.thirtyDayAvgMinutes  95 non-null     float64
 23  levels.summary.rem.count                  95 non-null     float64
 24  levels.summary.rem.minutes                95 non-null     float64
 25  levels.summary.rem.thirtyDayAvgMinutes    95 non-null     float64
 26  levels.summary.wake.count                 95 non-null     float64
 27  levels.summary.wake.minutes               95 non-null     float64
 28  levels.summary.wake.thirtyDayAvgMinutes   95 non-null     float64
 29  levels.summary.asleep.count               5 non-null      float64
 30  levels.summary.asleep.minutes             5 non-null      float64
 31  levels.summary.awake.count                5 non-null      float64
 32  levels.summary.awake.minutes              5 non-null      float64
 33  levels.summary.restless.count             5 non-null      float64
 34  levels.summary.restless.minutes           5 non-null      float64
dtypes: bool(1), float64(18), int64(9), object(7)
memory usage: 26.8+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 35 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   dateOfSleep                               100 non-null    object
 1   duration                                  100 non-null    int64
 2   efficiency                                100 non-null    int64
 3   endTime                                   100 non-null    object
 4   infoCode                                  100 non-null    int64
 5   isMainSleep                               100 non-null    bool
 6   logId                                     100 non-null    int64
 7   logType                                   100 non-null    object
 8   minutesAfterWakeup                        100 non-null    int64
 9   minutesAsleep                             100 non-null    int64
 10  minutesAwake                              100 non-null    int64
 11  minutesToFallAsleep                       100 non-null    int64
 12  startTime                                 100 non-null    object
 13  timeInBed                                 100 non-null    int64
 14  type                                      100 non-null    object
 15  levels.data                               100 non-null    object
 16  levels.shortData                          96 non-null     object
 17  levels.summary.deep.count                 96 non-null     float64
 18  levels.summary.deep.minutes               96 non-null     float64
 19  levels.summary.deep.thirtyDayAvgMinutes   96 non-null     float64
 20  levels.summary.light.count                96 non-null     float64
 21  levels.summary.light.minutes              96 non-null     float64
 22  levels.summary.light.thirtyDayAvgMinutes  96 non-null     float64
 23  levels.summary.rem.count                  96 non-null     float64
 24  levels.summary.rem.minutes                96 non-null     float64
 25  levels.summary.rem.thirtyDayAvgMinutes    96 non-null     float64
 26  levels.summary.wake.count                 96 non-null     float64
 27  levels.summary.wake.minutes               96 non-null     float64
 28  levels.summary.wake.thirtyDayAvgMinutes   96 non-null     float64
 29  levels.summary.asleep.count               4 non-null      float64
 30  levels.summary.asleep.minutes             4 non-null      float64
 31  levels.summary.awake.count                4 non-null      float64
 32  levels.summary.awake.minutes              4 non-null      float64
 33  levels.summary.restless.count             4 non-null      float64
 34  levels.summary.restless.minutes           4 non-null      float64
dtypes: bool(1), float64(18), int64(9), object(7)
memory usage: 26.8+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 35 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   dateOfSleep                               100 non-null    object
 1   duration                                  100 non-null    int64
 2   efficiency                                100 non-null    int64
 3   endTime                                   100 non-null    object
 4   infoCode                                  100 non-null    int64
 5   isMainSleep                               100 non-null    bool
 6   logId                                     100 non-null    int64
 7   logType                                   100 non-null    object
 8   minutesAfterWakeup                        100 non-null    int64
 9   minutesAsleep                             100 non-null    int64
 10  minutesAwake                              100 non-null    int64
 11  minutesToFallAsleep                       100 non-null    int64
 12  startTime                                 100 non-null    object
 13  timeInBed                                 100 non-null    int64
 14  type                                      100 non-null    object
 15  levels.data                               100 non-null    object
 16  levels.shortData                          98 non-null     object
 17  levels.summary.deep.count                 98 non-null     float64
 18  levels.summary.deep.minutes               98 non-null     float64
 19  levels.summary.deep.thirtyDayAvgMinutes   98 non-null     float64
 20  levels.summary.light.count                98 non-null     float64
 21  levels.summary.light.minutes              98 non-null     float64
 22  levels.summary.light.thirtyDayAvgMinutes  98 non-null     float64
 23  levels.summary.rem.count                  98 non-null     float64
 24  levels.summary.rem.minutes                98 non-null     float64
 25  levels.summary.rem.thirtyDayAvgMinutes    98 non-null     float64
 26  levels.summary.wake.count                 98 non-null     float64
 27  levels.summary.wake.minutes               98 non-null     float64
 28  levels.summary.wake.thirtyDayAvgMinutes   98 non-null     float64
 29  levels.summary.asleep.count               2 non-null      float64
 30  levels.summary.asleep.minutes             2 non-null      float64
 31  levels.summary.awake.count                2 non-null      float64
 32  levels.summary.awake.minutes              2 non-null      float64
 33  levels.summary.restless.count             2 non-null      float64
 34  levels.summary.restless.minutes           2 non-null      float64
dtypes: bool(1), float64(18), int64(9), object(7)
memory usage: 26.8+ KB
None

In [31]:
print(sleep_df.columns)
print(list(sleep_df.dtypes))

Index(['dateOfSleep', 'duration', 'efficiency', 'endTime', 'infoCode',
       'isMainSleep', 'logId', 'logType', 'minutesAfterWakeup',
       'minutesAsleep', 'minutesAwake', 'minutesToFallAsleep', 'startTime',
       'timeInBed', 'type', 'levels.data', 'levels.shortData',
       'levels.summary.deep.count', 'levels.summary.deep.minutes',
       'levels.summary.deep.thirtyDayAvgMinutes', 'levels.summary.light.count',
       'levels.summary.light.minutes',
       'levels.summary.light.thirtyDayAvgMinutes', 'levels.summary.rem.count',
       'levels.summary.rem.minutes', 'levels.summary.rem.thirtyDayAvgMinutes',
       'levels.summary.wake.count', 'levels.summary.wake.minutes',
       'levels.summary.wake.thirtyDayAvgMinutes',
       'levels.summary.asleep.count', 'levels.summary.asleep.minutes',
       'levels.summary.awake.count', 'levels.summary.awake.minutes',
       'levels.summary.restless.count', 'levels.summary.restless.minutes'],
      dtype='object')
[dtype('O'), dtype('int64'), dtype('int64'), dtype('O'), dtype('int64'), dtype('bool'), dtype('int64'), dtype('O'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('O'), dtype('int64'), dtype('O'), dtype('O'), dtype('O'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64')]

In [32]:
# sleep_df = sleep_df[['endTime', 'startTime', 'duration', 'efficiency', 'isMainSleep']]
# sleep_df_2 = sleep_df_2[['endTime', 'startTime', 'duration', 'efficiency', 'isMainSleep']]
# sleep_df_3 = sleep_df_3[['endTime', 'startTime', 'duration', 'efficiency', 'isMainSleep']]
# print(sleep_df.info())
# print(sleep_df_2.info())
# print(sleep_df_3.info())

In [33]:
sleep_df = pd.concat([sleep_df, sleep_df_2, sleep_df_3], ignore_index=True)
sleep_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 35 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   dateOfSleep                               300 non-null    object
 1   duration                                  300 non-null    int64
 2   efficiency                                300 non-null    int64
 3   endTime                                   300 non-null    object
 4   infoCode                                  300 non-null    int64
 5   isMainSleep                               300 non-null    bool
 6   logId                                     300 non-null    int64
 7   logType                                   300 non-null    object
 8   minutesAfterWakeup                        300 non-null    int64
 9   minutesAsleep                             300 non-null    int64
 10  minutesAwake                              300 non-null    int64
 11  minutesToFallAsleep                       300 non-null    int64
 12  startTime                                 300 non-null    object
 13  timeInBed                                 300 non-null    int64
 14  type                                      300 non-null    object
 15  levels.data                               300 non-null    object
 16  levels.shortData                          289 non-null    object
 17  levels.summary.deep.count                 289 non-null    float64
 18  levels.summary.deep.minutes               289 non-null    float64
 19  levels.summary.deep.thirtyDayAvgMinutes   289 non-null    float64
 20  levels.summary.light.count                289 non-null    float64
 21  levels.summary.light.minutes              289 non-null    float64
 22  levels.summary.light.thirtyDayAvgMinutes  289 non-null    float64
 23  levels.summary.rem.count                  289 non-null    float64
 24  levels.summary.rem.minutes                289 non-null    float64
 25  levels.summary.rem.thirtyDayAvgMinutes    289 non-null    float64
 26  levels.summary.wake.count                 289 non-null    float64
 27  levels.summary.wake.minutes               289 non-null    float64
 28  levels.summary.wake.thirtyDayAvgMinutes   289 non-null    float64
 29  levels.summary.asleep.count               11 non-null     float64
 30  levels.summary.asleep.minutes             11 non-null     float64
 31  levels.summary.awake.count                11 non-null     float64
 32  levels.summary.awake.minutes              11 non-null     float64
 33  levels.summary.restless.count             11 non-null     float64
 34  levels.summary.restless.minutes           11 non-null     float64
dtypes: bool(1), float64(18), int64(9), object(7)
memory usage: 80.1+ KB

In [34]:
#ToDo: Add to sleep score csv, combine data.

In [35]:
sleep_score_csv = pd.read_csv('../data/raw_data/Takeout/Fitbit/Sleep Score/sleep_score.csv')
print(sleep_score_csv.head(2))
sleep_score_csv.info()

   sleep_log_entry_id             timestamp  overall_score  composition_score  \
0         46799586724  2024-09-09T10:33:30Z             79                 19
1         46787402745  2024-09-08T10:44:00Z             84                 20

   revitalization_score  duration_score  deep_sleep_in_minutes  \
0                    21              39                     94
1                    20              44                     90

   resting_heart_rate  restlessness
0                  57      0.091887
1                  58      0.108423
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 276 entries, 0 to 275
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sleep_log_entry_id     276 non-null    int64
 1   timestamp              276 non-null    object
 2   overall_score          276 non-null    int64
 3   composition_score      276 non-null    int64
 4   revitalization_score   276 non-null    int64
 5   duration_score         276 non-null    int64
 6   deep_sleep_in_minutes  276 non-null    int64
 7   resting_heart_rate     276 non-null    int64
 8   restlessness           276 non-null    float64
dtypes: float64(1), int64(7), object(1)
memory usage: 19.5+ KB

In [36]:
sleep_df['minutesToFallAsleep'].value_counts()
sleep_df['type'].value_counts()
sleep_df['minutesAfterWakeup'].value_counts()

minutesAfterWakeup
0     219
1      21
4      10
2       9
8       7
3       7
5       6
7       5
6       4
11      3
10      3
9       2
13      2
15      1
12      1
Name: count, dtype: int64

In [37]:
sleep_df.applymap(type).eq(list).any()

C:\Users\Saatvik Sandal\AppData\Local\Temp\ipykernel_94868\1381171481.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  sleep_df.applymap(type).eq(list).any()

dateOfSleep                                 False
duration                                    False
efficiency                                  False
endTime                                     False
infoCode                                    False
isMainSleep                                 False
logId                                       False
logType                                     False
minutesAfterWakeup                          False
minutesAsleep                               False
minutesAwake                                False
minutesToFallAsleep                         False
startTime                                   False
timeInBed                                   False
type                                        False
levels.data                                  True
levels.shortData                             True
levels.summary.deep.count                   False
levels.summary.deep.minutes                 False
levels.summary.deep.thirtyDayAvgMinutes     False
levels.summary.light.count                  False
levels.summary.light.minutes                False
levels.summary.light.thirtyDayAvgMinutes    False
levels.summary.rem.count                    False
levels.summary.rem.minutes                  False
levels.summary.rem.thirtyDayAvgMinutes      False
levels.summary.wake.count                   False
levels.summary.wake.minutes                 False
levels.summary.wake.thirtyDayAvgMinutes     False
levels.summary.asleep.count                 False
levels.summary.asleep.minutes               False
levels.summary.awake.count                  False
levels.summary.awake.minutes                False
levels.summary.restless.count               False
levels.summary.restless.minutes             False
dtype: bool

In [38]:
sleep_df[['isMainSleep', 'logId']].groupby('isMainSleep').nunique()

             logId
isMainSleep
False            7
True           293

In [39]:
print(sleep_df.tail(2))
print(sleep_score_csv.tail(15))

    dateOfSleep  duration  efficiency                  endTime  infoCode  \
298  2024-09-21  31680000          91  2024-09-21T11:59:00.000         0
299  2024-09-22  23400000          95  2024-09-22T11:38:00.000         0

     isMainSleep        logId        logType  minutesAfterWakeup  \
298         True  46919614889  auto_detected                   0
299         True  46930406763  auto_detected                   6

     minutesAsleep  ...  levels.summary.rem.thirtyDayAvgMinutes  \
298            440  ...                                    97.0
299            347  ...                                    96.0

     levels.summary.wake.count levels.summary.wake.minutes  \
298                       29.0                        88.0
299                       21.0                        43.0

     levels.summary.wake.thirtyDayAvgMinutes levels.summary.asleep.count  \
298                                     58.0                         NaN
299                                     59.0                         NaN

    levels.summary.asleep.minutes levels.summary.awake.count  \
298                           NaN                        NaN
299                           NaN                        NaN

     levels.summary.awake.minutes  levels.summary.restless.count  \
298                           NaN                            NaN
299                           NaN                            NaN

     levels.summary.restless.minutes
298                              NaN
299                              NaN

[2 rows x 35 columns]
     sleep_log_entry_id             timestamp  overall_score  \
261         43762262512  2023-12-09T10:14:30Z             85
262         43752289165  2023-12-08T08:14:30Z             80
263         43738653527  2023-12-07T07:59:30Z             80
264         43727216668  2023-12-06T08:25:30Z             80
265         43714580116  2023-12-05T08:24:30Z             83
266         43702917553  2023-12-04T08:40:30Z             84
267         43669822234  2023-12-01T08:36:30Z             83
268         43660623316  2023-11-30T08:32:30Z             78
269         43646252339  2023-11-29T08:09:30Z             79
270         43633513865  2023-11-28T08:40:00Z             73
271         43621802223  2023-11-27T08:06:30Z             80
272         43613017101  2023-11-26T09:53:00Z             85
273         43602769603  2023-11-25T09:46:30Z             76
274         43592244818  2023-11-24T10:51:30Z             85
275         43581685752  2023-11-23T12:51:00Z             83

     composition_score  revitalization_score  duration_score  \
261                 22                    21              42
262                 20                    20              40
263                 20                    21              39
264                 21                    21              38
265                 22                    22              39
266                 22                    23              39
267                 21                    22              40
268                 20                    20              38
269                 21                    21              37
270                 18                    21              34
271                 21                    23              36
272                 21                    22              42
273                 22                    19              35
274                 22                    22              41
275                 21                    19              43

     deep_sleep_in_minutes  resting_heart_rate  restlessness
261                     84                  65      0.062308
262                     88                  63      0.079034
263                     70                  62      0.066906
264                     57                  61      0.062771
265                    100                  61      0.071661
266                    101                  63      0.067416
267                     65                  63      0.079334
268                     36                  62      0.096061
269                     57                  61      0.073326
270                     66                  61      0.089130
271                     63                  63      0.065834
272                     77                  64      0.075884
273                     93                  66      0.139683
274                     94                  68      0.092902
275                    117                  70      0.086887

In [40]:
#Get rid of non-main sleep rows, not needed for this study
sleep_df = sleep_df[sleep_df['isMainSleep']]
print(type(sleep_df['endTime'][0]))
sleep_df.info()

<class 'str'>
<class 'pandas.core.frame.DataFrame'>
Index: 293 entries, 0 to 299
Data columns (total 35 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   dateOfSleep                               293 non-null    object
 1   duration                                  293 non-null    int64
 2   efficiency                                293 non-null    int64
 3   endTime                                   293 non-null    object
 4   infoCode                                  293 non-null    int64
 5   isMainSleep                               293 non-null    bool
 6   logId                                     293 non-null    int64
 7   logType                                   293 non-null    object
 8   minutesAfterWakeup                        293 non-null    int64
 9   minutesAsleep                             293 non-null    int64
 10  minutesAwake                              293 non-null    int64
 11  minutesToFallAsleep                       293 non-null    int64
 12  startTime                                 293 non-null    object
 13  timeInBed                                 293 non-null    int64
 14  type                                      293 non-null    object
 15  levels.data                               293 non-null    object
 16  levels.shortData                          289 non-null    object
 17  levels.summary.deep.count                 289 non-null    float64
 18  levels.summary.deep.minutes               289 non-null    float64
 19  levels.summary.deep.thirtyDayAvgMinutes   289 non-null    float64
 20  levels.summary.light.count                289 non-null    float64
 21  levels.summary.light.minutes              289 non-null    float64
 22  levels.summary.light.thirtyDayAvgMinutes  289 non-null    float64
 23  levels.summary.rem.count                  289 non-null    float64
 24  levels.summary.rem.minutes                289 non-null    float64
 25  levels.summary.rem.thirtyDayAvgMinutes    289 non-null    float64
 26  levels.summary.wake.count                 289 non-null    float64
 27  levels.summary.wake.minutes               289 non-null    float64
 28  levels.summary.wake.thirtyDayAvgMinutes   289 non-null    float64
 29  levels.summary.asleep.count               4 non-null      float64
 30  levels.summary.asleep.minutes             4 non-null      float64
 31  levels.summary.awake.count                4 non-null      float64
 32  levels.summary.awake.minutes              4 non-null      float64
 33  levels.summary.restless.count             4 non-null      float64
 34  levels.summary.restless.minutes           4 non-null      float64
dtypes: bool(1), float64(18), int64(9), object(7)
memory usage: 88.5+ KB

In [41]:
#need to merge the two tables, likely on sleep_df.info() endTime onto sleep_score_csv timestamp (the timestamp seems to be the time that I wake up...)
#2024-08-05T08:07:30.000
test = sleep_df['endTime'][1]
date_test = dt.datetime.strptime(test, "%Y-%m-%dT%H:%M:%S.%f")
print(date_test.month)

test_t = sleep_score_csv['timestamp'][0]
print((test_t))
print((test))

date_test_t = dt.datetime.strptime(test_t, '%Y-%m-%dT%H:%M:%SZ')


print(date_test.year == date_test_t.year)
print(date_test.month == date_test_t.month)
print(date_test.day == date_test_t.day)

# test_t = sleep_score_csv['timestamp'][249]
# print((test_t))
# date_test_tt = dt.datetime.strptime(test_t, '%m/%d/%Y')
# #print(date_test_t.day)

AttributeError: 'list' object has no attribute 'datetime'

In [ ]:
# for sleep df use this: 
# dt.datetime.strptime(test, "%Y-%m-%dT%H:%M:%S.%f")

# for first bit of sleep csv use: 
# dt.datetime.strptime(test_t, '%Y-%m-%dT%H:%M:%SZ')

# for last bit of sleep csv use: 
# dt.datetime.strptime(test_t, '%m/%d/%Y')

In [ ]:
#Actually im going to standardize the string formats so that comparing datetime objects is easy

In [42]:
test = test[0:10]
test_t = test[0:10]
date_test = dt.datetime.strptime(test, "%Y-%m-%d")
date_test_t = dt.datetime.strptime(test_t, '%Y-%m-%d')
# print(date_test == date_test_t == date_test_tt)
# print(date_test)
# print(date_test_tt)
# dummy_string = '11/23/2023'
# dummy_datetime = dt.datetime.strptime(dummy_string, '%m/%d/%Y')
# print(date_test == date_test_t == dummy_datetime)

AttributeError: 'list' object has no attribute 'datetime'

In [43]:
#Now they can be standardized, so now I need to convert the columns, and then merge them.

In [44]:
print(sleep_df.iloc[0])
sleep_df = sleep_df.drop(0)
print(sleep_df.iloc[0])

dateOfSleep                                                                        2023-11-23
duration                                                                             37260000
efficiency                                                                                 91
endTime                                                               2023-11-23T12:51:00.000
infoCode                                                                                    0
isMainSleep                                                                              True
logId                                                                             43581685752
logType                                                                         auto_detected
minutesAfterWakeup                                                                          0
minutesAsleep                                                                             536
minutesAwake                                                                               85
minutesToFallAsleep                                                                         0
startTime                                                             2023-11-23T02:29:30.000
timeInBed                                                                                 621
type                                                                                   stages
levels.data                                 [{'dateTime': '2023-11-23T02:29:30.000', 'leve...
levels.shortData                            [{'dateTime': '2023-11-23T03:35:00.000', 'leve...
levels.summary.deep.count                                                                 5.0
levels.summary.deep.minutes                                                             117.0
levels.summary.deep.thirtyDayAvgMinutes                                                   0.0
levels.summary.light.count                                                               35.0
levels.summary.light.minutes                                                            306.0
levels.summary.light.thirtyDayAvgMinutes                                                  0.0
levels.summary.rem.count                                                                 11.0
levels.summary.rem.minutes                                                              113.0
levels.summary.rem.thirtyDayAvgMinutes                                                    0.0
levels.summary.wake.count                                                                35.0
levels.summary.wake.minutes                                                              85.0
levels.summary.wake.thirtyDayAvgMinutes                                                   0.0
levels.summary.asleep.count                                                               NaN
levels.summary.asleep.minutes                                                             NaN
levels.summary.awake.count                                                                NaN
levels.summary.awake.minutes                                                              NaN
levels.summary.restless.count                                                             NaN
levels.summary.restless.minutes                                                           NaN
Name: 0, dtype: object
dateOfSleep                                                                        2023-11-24
duration                                                                             29520000
efficiency                                                                                 92
endTime                                                               2023-11-24T10:51:30.000
infoCode                                                                                    0
isMainSleep                                                                              True
logId                                                                             43592244818
logType                                                                         auto_detected
minutesAfterWakeup                                                                          0
minutesAsleep                                                                             427
minutesAwake                                                                               65
minutesToFallAsleep                                                                         0
startTime                                                             2023-11-24T02:39:00.000
timeInBed                                                                                 492
type                                                                                   stages
levels.data                                 [{'dateTime': '2023-11-24T02:39:00.000', 'leve...
levels.shortData                            [{'dateTime': '2023-11-24T04:06:30.000', 'leve...
levels.summary.deep.count                                                                 4.0
levels.summary.deep.minutes                                                              94.0
levels.summary.deep.thirtyDayAvgMinutes                                                 117.0
levels.summary.light.count                                                               25.0
levels.summary.light.minutes                                                            234.0
levels.summary.light.thirtyDayAvgMinutes                                                306.0
levels.summary.rem.count                                                                  8.0
levels.summary.rem.minutes                                                               99.0
levels.summary.rem.thirtyDayAvgMinutes                                                  113.0
levels.summary.wake.count                                                                27.0
levels.summary.wake.minutes                                                              65.0
levels.summary.wake.thirtyDayAvgMinutes                                                  85.0
levels.summary.asleep.count                                                               NaN
levels.summary.asleep.minutes                                                             NaN
levels.summary.awake.count                                                                NaN
levels.summary.awake.minutes                                                              NaN
levels.summary.restless.count                                                             NaN
levels.summary.restless.minutes                                                           NaN
Name: 1, dtype: object

In [45]:
#going to add a column. the sleep_df endtime correlates with the sleep_csv timestamp, will make a copy and change them.
sleep_df['datetime_key'] = sleep_df['endTime']
sleep_score_csv['datetime_key'] = sleep_score_csv['timestamp']

In [46]:
#add datetime column for each df containing the date of sleep, then merge

In [47]:
sleep_df['datetime_key'] = sleep_df['datetime_key'].str.slice(start=0, stop=10)
sleep_score_csv['datetime_key'] = sleep_score_csv['datetime_key'].str.slice(start=0, stop=10)
#dt.datetime.strptime(test_t, '%Y-%m-%d')

In [48]:
sleep_df['datetime_key'] = pd.to_datetime(sleep_df['datetime_key'])
sleep_score_csv['datetime_key'] = pd.to_datetime(sleep_score_csv['datetime_key'])

In [49]:
print(sleep_df.info())
print(sleep_score_csv.info())

<class 'pandas.core.frame.DataFrame'>
Index: 292 entries, 1 to 299
Data columns (total 36 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   dateOfSleep                               292 non-null    object
 1   duration                                  292 non-null    int64
 2   efficiency                                292 non-null    int64
 3   endTime                                   292 non-null    object
 4   infoCode                                  292 non-null    int64
 5   isMainSleep                               292 non-null    bool
 6   logId                                     292 non-null    int64
 7   logType                                   292 non-null    object
 8   minutesAfterWakeup                        292 non-null    int64
 9   minutesAsleep                             292 non-null    int64
 10  minutesAwake                              292 non-null    int64
 11  minutesToFallAsleep                       292 non-null    int64
 12  startTime                                 292 non-null    object
 13  timeInBed                                 292 non-null    int64
 14  type                                      292 non-null    object
 15  levels.data                               292 non-null    object
 16  levels.shortData                          288 non-null    object
 17  levels.summary.deep.count                 288 non-null    float64
 18  levels.summary.deep.minutes               288 non-null    float64
 19  levels.summary.deep.thirtyDayAvgMinutes   288 non-null    float64
 20  levels.summary.light.count                288 non-null    float64
 21  levels.summary.light.minutes              288 non-null    float64
 22  levels.summary.light.thirtyDayAvgMinutes  288 non-null    float64
 23  levels.summary.rem.count                  288 non-null    float64
 24  levels.summary.rem.minutes                288 non-null    float64
 25  levels.summary.rem.thirtyDayAvgMinutes    288 non-null    float64
 26  levels.summary.wake.count                 288 non-null    float64
 27  levels.summary.wake.minutes               288 non-null    float64
 28  levels.summary.wake.thirtyDayAvgMinutes   288 non-null    float64
 29  levels.summary.asleep.count               4 non-null      float64
 30  levels.summary.asleep.minutes             4 non-null      float64
 31  levels.summary.awake.count                4 non-null      float64
 32  levels.summary.awake.minutes              4 non-null      float64
 33  levels.summary.restless.count             4 non-null      float64
 34  levels.summary.restless.minutes           4 non-null      float64
 35  datetime_key                              292 non-null    datetime64[ns]
dtypes: bool(1), datetime64[ns](1), float64(18), int64(9), object(7)
memory usage: 82.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 276 entries, 0 to 275
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sleep_log_entry_id     276 non-null    int64
 1   timestamp              276 non-null    object
 2   overall_score          276 non-null    int64
 3   composition_score      276 non-null    int64
 4   revitalization_score   276 non-null    int64
 5   duration_score         276 non-null    int64
 6   deep_sleep_in_minutes  276 non-null    int64
 7   resting_heart_rate     276 non-null    int64
 8   restlessness           276 non-null    float64
 9   datetime_key           276 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(7), object(1)
memory usage: 21.7+ KB
None

In [50]:
#now inner join on datetime_key. then convert all to csv files.

ready_sleep = sleep_df.merge(sleep_score_csv, on = 'datetime_key', how='inner')
print(ready_sleep.info())
ready_sleep.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 45 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   dateOfSleep                               275 non-null    object
 1   duration                                  275 non-null    int64
 2   efficiency                                275 non-null    int64
 3   endTime                                   275 non-null    object
 4   infoCode                                  275 non-null    int64
 5   isMainSleep                               275 non-null    bool
 6   logId                                     275 non-null    int64
 7   logType                                   275 non-null    object
 8   minutesAfterWakeup                        275 non-null    int64
 9   minutesAsleep                             275 non-null    int64
 10  minutesAwake                              275 non-null    int64
 11  minutesToFallAsleep                       275 non-null    int64
 12  startTime                                 275 non-null    object
 13  timeInBed                                 275 non-null    int64
 14  type                                      275 non-null    object
 15  levels.data                               275 non-null    object
 16  levels.shortData                          275 non-null    object
 17  levels.summary.deep.count                 275 non-null    float64
 18  levels.summary.deep.minutes               275 non-null    float64
 19  levels.summary.deep.thirtyDayAvgMinutes   275 non-null    float64
 20  levels.summary.light.count                275 non-null    float64
 21  levels.summary.light.minutes              275 non-null    float64
 22  levels.summary.light.thirtyDayAvgMinutes  275 non-null    float64
 23  levels.summary.rem.count                  275 non-null    float64
 24  levels.summary.rem.minutes                275 non-null    float64
 25  levels.summary.rem.thirtyDayAvgMinutes    275 non-null    float64
 26  levels.summary.wake.count                 275 non-null    float64
 27  levels.summary.wake.minutes               275 non-null    float64
 28  levels.summary.wake.thirtyDayAvgMinutes   275 non-null    float64
 29  levels.summary.asleep.count               0 non-null      float64
 30  levels.summary.asleep.minutes             0 non-null      float64
 31  levels.summary.awake.count                0 non-null      float64
 32  levels.summary.awake.minutes              0 non-null      float64
 33  levels.summary.restless.count             0 non-null      float64
 34  levels.summary.restless.minutes           0 non-null      float64
 35  datetime_key                              275 non-null    datetime64[ns]
 36  sleep_log_entry_id                        275 non-null    int64
 37  timestamp                                 275 non-null    object
 38  overall_score                             275 non-null    int64
 39  composition_score                         275 non-null    int64
 40  revitalization_score                      275 non-null    int64
 41  duration_score                            275 non-null    int64
 42  deep_sleep_in_minutes                     275 non-null    int64
 43  resting_heart_rate                        275 non-null    int64
 44  restlessness                              275 non-null    float64
dtypes: bool(1), datetime64[ns](1), float64(19), int64(16), object(8)
memory usage: 94.9+ KB
None

,dateOfSleep,duration,efficiency,endTime,infoCode,isMainSleep,logId,logType,minutesAfterWakeup,minutesAsleep,...,datetime_key,sleep_log_entry_id,timestamp,overall_score,composition_score,revitalization_score,duration_score,deep_sleep_in_minutes,resting_heart_rate,restlessness
0,2023-11-24,29520000,92,2023-11-24T10:51:30.000,0,True,43592244818,auto_detected,0,427,...,2023-11-24,43592244818,2023-11-24T10:51:30Z,85,22,22,41,94,68,0.092902
1,2023-11-25,28680000,86,2023-11-25T09:46:30.000,0,True,43602769603,auto_detected,8,398,...,2023-11-25,43602769603,2023-11-25T09:46:30Z,76,22,19,35,93,66,0.139683
2,2023-11-26,29760000,92,2023-11-26T09:53:00.000,0,True,43613017101,auto_detected,0,439,...,2023-11-26,43613017101,2023-11-26T09:53:00Z,85,21,22,42,77,64,0.075884
3,2023-11-27,26400000,93,2023-11-27T08:06:30.000,0,True,43621802223,auto_detected,0,385,...,2023-11-27,43621802223,2023-11-27T08:06:30Z,80,21,23,36,63,63,0.065834
4,2023-11-28,28140000,90,2023-11-28T08:40:00.000,0,True,43633513865,manual,0,393,...,2023-11-28,43633513865,2023-11-28T08:40:00Z,73,18,21,34,66,61,0.089130

# Skin Temperature Log

In [51]:
# Take: dateTime, value
skin_df_arr = []
for i in range(1,10):
    file_path = f'../data/raw_data/get_skin_{i}.json'
    
    f = open(file_path)
    data = json.load(f)
    skin_df = pd.DataFrame.from_dict(pd.json_normalize(data['tempSkin']), orient='columns')
    skin_df = skin_df[['dateTime', 'value.nightlyRelative']]
    skin_df_arr.append(skin_df)
    
skin_df_arr[0].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dateTime               24 non-null     object
 1   value.nightlyRelative  24 non-null     float64
dtypes: float64(1), object(1)
memory usage: 516.0+ bytes

In [52]:
for i in range(1, len(skin_df_arr)):
    skin_df_arr[0] = pd.concat([skin_df_arr[0], skin_df_arr[i]], ignore_index=True)
    #print(i)
    
print(skin_df_arr[0].info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dateTime               258 non-null    object
 1   value.nightlyRelative  258 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.2+ KB
None

In [53]:
skin_df = skin_df_arr[0]
skin_df.head(2)

     dateTime  value.nightlyRelative
0  2023-11-26                    0.1
1  2023-11-27                   -0.4

# Heart Rate Variability Log

In [54]:
# Take: dateTime, dailyRmssd, deepRmssd
hrv_df_arr = []
for i in range(1,10):
    file_path = f'../data/raw_data/get_hrv_{i}.json'
    
    f = open(file_path)
    data = json.load(f)
    hrv_df = pd.DataFrame.from_dict(pd.json_normalize(data['hrv']), orient='columns')
    hrv_df_arr.append(hrv_df)
    
hrv_df_arr[0].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   dateTime          29 non-null     object
 1   value.dailyRmssd  29 non-null     float64
 2   value.deepRmssd   29 non-null     float64
dtypes: float64(2), object(1)
memory usage: 828.0+ bytes

In [55]:
for i in range(1, len(hrv_df_arr)):
    hrv_df_arr[0] = pd.concat([hrv_df_arr[0], hrv_df_arr[i]], ignore_index=True)
    
print(hrv_df_arr[0].info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263 entries, 0 to 262
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   dateTime          263 non-null    object
 1   value.dailyRmssd  263 non-null    float64
 2   value.deepRmssd   263 non-null    float64
dtypes: float64(2), object(1)
memory usage: 6.3+ KB
None

In [56]:
hrv_df = hrv_df_arr[0]
hrv_df.head(2)

     dateTime  value.dailyRmssd  value.deepRmssd
0  2023-11-23            30.614           31.604
1  2023-11-24            84.414           91.716

# Breathing Rate Log

In [57]:
# Take: dateTime, breathingRate

In [58]:
# Take: dateTime, dailyRmssd, deepRmssd
br_df_arr = []
for i in range(1,10):
    file_path = f'../data/raw_data/get_br_{i}.json'
    
    f = open(file_path)
    data = json.load(f)
    br_df = pd.DataFrame.from_dict(pd.json_normalize(data['br']), orient='columns')
    br_df_arr.append(br_df)
    
br_df_arr[0].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dateTime             29 non-null     object
 1   value.breathingRate  29 non-null     float64
dtypes: float64(1), object(1)
memory usage: 596.0+ bytes

In [59]:
for i in range(1, len(br_df_arr)):
    br_df_arr[0] = pd.concat([br_df_arr[0], br_df_arr[i]], ignore_index=True)
    
print(br_df_arr[0].info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dateTime             262 non-null    object
 1   value.breathingRate  262 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.2+ KB
None

In [60]:
br_df = br_df_arr[0]
br_df.head(2)

     dateTime  value.breathingRate
0  2023-11-23                 16.6
1  2023-11-24                 14.6

In [61]:
# See how to incorporate sleep score, merge tables, find if I need to match keys...

In [ ]:
#now get a list of dfs, convert to csvs, and then begin analysis on excel...

In [ ]:
# list_of_dfs_to_csv = [activity_df, ready_sleep, skin_df, hrv_df, br_df]
# list_of_dfs_to_csv_str = ['activity_csv', 'ready_sleep_csv', 'skin_csv', 'hrv_df_csv', 'br_csv']

In [ ]:
# for idx, df in enumerate(list_of_dfs_to_csv):
    
#     df.to_csv('F:/jupyter_workspace/FishBit/wrangled_data/'+list_of_dfs_to_csv_str[idx]+'.csv', index=False)

In [ ]:
#Thanks for watching